'use client'

import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Media } from '@/payload-types'

// Local type definition until Payload types are regenerated
export type DomainsBlockProps = {
  title: string
  subtitle: string
  tabs: {
    id?: string // Generated by Payload
    tabLabel: string
    moduleTag?: string | null
    subTitle?: string | null
    mainTitle: string
    description: string
    hardware?: string | null
    image: number | Media
  }[]
}

export const DomainsBlock: React.FC<DomainsBlockProps> = (props) => {
  const { title, subtitle, tabs } = props
  const [activeTabId, setActiveTabId] = useState<string | null>(null)

  // Initialize active tab once tabs are available
  useEffect(() => {
    if (tabs && tabs.length > 0 && !activeTabId) {
      setActiveTabId(tabs[0].id || '0')
    }
  }, [tabs, activeTabId])

  // Helper to get image URL safely
  const getImageUrl = (media: number | Media | null | undefined) => {
    if (!media) return ''
    if (typeof media === 'number') return '' // Should ideally resolve relation
    return media.url || ''
  }

  if (!tabs || tabs.length === 0) return null

  return (
    <section className="overflow-hidden bg-[#050505] py-20 md:py-32 text-white selection:bg-[#FFB800] selection:text-black">
      <div className="container mx-auto max-w-[1600px] px-4">
        {/* Section Header */}
        <div className="mb-16 md:mb-24 text-center">
          <h2 className="mb-4 font-heading text-3xl font-bold tracking-tight md:text-[40px] leading-tight">
            {title}
          </h2>
          <p className="mx-auto max-w-2xl text-lg md:text-xl font-medium text-white/50">
            {subtitle}
          </p>
        </div>

        <div className="grid grid-cols-1 items-start gap-12 lg:grid-cols-12">
          {/* LEFT: Navigation Tabs */}
          <div className="flex flex-col rounded-md border border-white/5 bg-[#0A0A0A] overflow-hidden transition-all duration-500 hover:border-[#FFB800]/30 lg:col-span-3">
            {tabs.map((tab, index) => {
              const tabId = tab.id || index.toString()
              const isActive = activeTabId === tabId
              const isLast = index === tabs.length - 1

              return (
                <button
                  key={tabId}
                  onClick={() => setActiveTabId(tabId)}
                  className={`
                    group relative flex flex-col items-start p-8 text-left transition-all duration-300
                    ${!isLast ? 'border-b border-white/5' : ''}
                    ${isActive ? 'bg-white/[0.02]' : 'hover:bg-white/[0.02]'}
                  `}
                >
                  {/* Active Indicator Line */}
                  {isActive && (
                    <motion.div
                      layoutId="activeTabIndicator"
                      className="absolute left-0 top-0 bottom-0 w-1 bg-[#FFB800]"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                    />
                  )}

                  <span className={`mb-3 font-mono text-xl font-bold ${isActive ? 'text-[#FFB800]' : 'text-[#FFB800]/70'}`}>
                    {String(index + 1).padStart(2, '0')}.
                  </span>
                  <span className={`max-w-[200px] font-heading text-lg font-bold leading-tight ${isActive ? 'text-white' : 'text-white/60'}`}>
                    {tab.tabLabel}
                  </span>
                </button>
              )
            })}
          </div>

          {/* RIGHT: Content Card */}
          <div className="lg:col-span-9">
            <div className="group relative flex min-h-[500px] flex-col justify-between rounded-md border border-white/5 bg-[#0A0A0A] p-8 md:p-12 transition-all duration-500 hover:border-[#FFB800]/30">
              <AnimatePresence mode="wait">
                {tabs.map((tab, index) => {
                  const tabId = tab.id || index.toString()
                  if (tabId !== activeTabId) return null

                  const imageUrl = getImageUrl(tab.image)

                  return (
                    <motion.div
                      key={tabId}
                      initial={{ opacity: 0, x: 10 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: -10 }}
                      transition={{ duration: 0.3 }}
                      className="grid h-full grid-cols-1 gap-12 md:grid-cols-2"
                    >
                      {/* Text Content */}
                      <div className="relative z-10 flex h-full flex-col">
                        <div className="mb-6">
                          <span className="font-mono text-[10px] uppercase tracking-widest text-white/40">
                            {tab.moduleTag}
                          </span>
                        </div>

                        <h4 className="mb-2 text-sm font-bold text-[#FFB800]">
                          {tab.subTitle}
                        </h4>

                        <h3 className="mb-6 font-heading text-4xl font-bold leading-[1.1] text-white md:text-5xl">
                          {tab.mainTitle}
                        </h3>

                        <p className="mb-12 max-w-sm font-sans text-sm leading-relaxed text-white/50">
                          {tab.description}
                        </p>

                        <div className="mt-auto border-t border-white/5 pt-6">
                          <span className="mb-1 block font-mono text-[10px] uppercase text-white/40">
                            Hardware
                          </span>
                          <span className="font-mono text-xs text-white/60">
                            {tab.hardware}
                          </span>
                        </div>
                      </div>

                      {/* Visual / Image Area */}
                      <div className="relative flex min-h-[300px] items-center justify-center md:min-h-0">
                        {/* Ambient Glow */}
                        <div className="pointer-events-none absolute bottom-10 left-1/2 size-48 -translate-x-1/2 rounded-full bg-[#FFB800] opacity-20 blur-[60px] transition-opacity duration-700 group-hover:opacity-40" />

                        {/* Tech Decorative Lines Container */}
                        <div className="pointer-events-none absolute inset-0 rounded-md border border-white/5 opacity-50">
                          <div className="absolute left-0 top-0 size-2 border-l border-t border-[#FFB800]" />
                          <div className="absolute right-0 top-0 size-2 border-r border-t border-[#FFB800]" />
                          <div className="absolute bottom-0 left-0 size-2 border-b border-l border-[#FFB800]" />
                          <div className="absolute bottom-0 right-0 size-2 border-b border-r border-[#FFB800]" />
                        </div>

                        {/* ACTUAL IMAGE RENDER */}
                        <div className="relative z-10 flex size-full items-center justify-center">
                          {imageUrl && (
                            <motion.img
                              src={imageUrl}
                              alt={tab.mainTitle}
                              className="h-auto w-[110%] translate-x-6 translate-y-6 object-contain drop-shadow-2xl md:w-[130%] md:translate-x-12 md:translate-y-12 transition-transform duration-700 group-hover:scale-105"
                              initial={{ y: 10, opacity: 0 }}
                              animate={{ y: 0, opacity: 1 }}
                              transition={{ duration: 0.5, delay: 0.1 }}
                            />
                          )}

                          {/* Subtle floating animation overlay */}
                          <motion.div
                            className="pointer-events-none absolute inset-0 z-20"
                            animate={{ y: [0, -10, 0] }}
                            transition={{ repeat: Infinity, duration: 6, ease: 'easeInOut' }}
                          />
                        </div>
                      </div>
                    </motion.div>
                  )
                })}
              </AnimatePresence>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
