'use client'

import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Media } from '@/payload-types'

// Local type definition until Payload types are regenerated
export type DomainsBlockProps = {
  title: string
  subtitle: string
  tabs: {
    id?: string // Generated by Payload
    tabLabel: string
    moduleTag?: string | null
    subTitle?: string | null
    mainTitle: string
    description: string
    hardware?: string | null
    image: number | Media
  }[]
}

export const DomainsBlock: React.FC<DomainsBlockProps> = (props) => {
  const { title, subtitle, tabs } = props
  const [activeTabId, setActiveTabId] = useState<string | null>(null)

  // Initialize active tab once tabs are available
  useEffect(() => {
    if (tabs && tabs.length > 0 && !activeTabId) {
      setActiveTabId(tabs[0].id || '0')
    }
  }, [tabs, activeTabId])

  // Helper to get image URL safely
  const getImageUrl = (media: number | Media | null | undefined) => {
    if (!media) return ''
    if (typeof media === 'number') return '' // Should ideally resolve relation
    return media.url || ''
  }

  if (!tabs || tabs.length === 0) return null

  return (
    <section className="py-32 bg-smatch-black text-white overflow-hidden">
      <div className="container mx-auto px-4 max-w-7xl">
        {/* Section Header */}
        <div className="text-center mb-24">
          <h2 className="font-heading text-3xl md:text-4xl font-bold mb-4 tracking-tight">
            {title}
          </h2>
          <p className="font-sans text-gray-500 max-w-2xl mx-auto text-base">
            {subtitle}
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
          {/* LEFT: Navigation Tabs */}
          <div className="lg:col-span-3 flex flex-col pt-4">
            {tabs.map((tab, index) => {
              const tabId = tab.id || index.toString()
              const isActive = activeTabId === tabId

              return (
                <button
                  key={tabId}
                  onClick={() => setActiveTabId(tabId)}
                  className={`
                    group flex flex-col items-start py-6 px-6 text-left transition-all duration-300 relative
                    ${isActive ? 'opacity-100' : 'opacity-40 hover:opacity-70'}
                  `}
                >
                  {/* Active Indicator Line */}
                  <div
                    className={`absolute left-0 top-6 bottom-6 w-[2px] transition-colors duration-300 ${
                      isActive ? 'bg-smatch-gold' : 'bg-gray-800'
                    }`}
                  />

                  <span className="text-smatch-gold text-sm font-bold font-mono mb-2">
                    {String(index + 1).padStart(2, '0')}.
                  </span>
                  <span className="font-heading text-xl font-bold leading-tight max-w-[150px]">
                    {tab.tabLabel}
                  </span>
                </button>
              )
            })}
          </div>

          {/* RIGHT: Content Card */}
          <div className="lg:col-span-9">
            <div className="bg-[#0F0F0F] rounded-2xl border border-white/5 p-8 md:p-12 min-h-[500px] relative flex flex-col justify-between">
              <AnimatePresence mode="wait">
                {tabs.map((tab, index) => {
                  const tabId = tab.id || index.toString()
                  if (tabId !== activeTabId) return null

                  const imageUrl = getImageUrl(tab.image)

                  return (
                    <motion.div
                      key={tabId}
                      initial={{ opacity: 0, x: 10 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: -10 }}
                      transition={{ duration: 0.3 }}
                      className="grid grid-cols-1 md:grid-cols-2 gap-12 h-full"
                    >
                      {/* Text Content */}
                      <div className="flex flex-col h-full relative z-10">
                        <div className="mb-6">
                          <span className="font-mono text-[10px] text-gray-600 tracking-widest uppercase">
                            {tab.moduleTag}
                          </span>
                        </div>

                        <h4 className="text-smatch-gold font-bold text-sm mb-2">
                          {tab.subTitle}
                        </h4>

                        <h3 className="font-heading text-4xl md:text-5xl font-bold text-white mb-6 leading-[1.1]">
                          {tab.mainTitle}
                        </h3>

                        <p className="font-sans text-gray-500 text-sm leading-relaxed mb-12 max-w-sm">
                          {tab.description}
                        </p>

                        <div className="mt-auto pt-6 border-t border-white/5">
                          <span className="block text-[10px] text-gray-600 uppercase mb-1 font-mono">
                            Hardware
                          </span>
                          <span className="font-mono text-xs text-gray-400">
                            {tab.hardware}
                          </span>
                        </div>
                      </div>

                      {/* Visual / Image Area */}
                      <div className="relative flex items-center justify-center min-h-[300px] md:min-h-0">
                        {/* The "Holo-Platform" Base Effects */}
                        <div className="absolute bottom-10 left-1/2 -translate-x-1/2 w-48 h-48 bg-smatch-gold/5 rounded-full blur-2xl pointer-events-none" />

                        {/* Tech Decorative Lines Container */}
                        <div className="absolute inset-0 border border-white/5 rounded-lg opacity-50 pointer-events-none">
                          <div className="absolute top-0 left-0 w-2 h-2 border-t border-l border-smatch-gold" />
                          <div className="absolute top-0 right-0 w-2 h-2 border-t border-r border-smatch-gold" />
                          <div className="absolute bottom-0 left-0 w-2 h-2 border-b border-l border-smatch-gold" />
                          <div className="absolute bottom-0 right-0 w-2 h-2 border-b border-r border-smatch-gold" />
                        </div>

                        {/* ACTUAL IMAGE RENDER */}
                        <div className="relative z-10 w-full h-full flex items-center justify-center">
                          {imageUrl && (
                            <motion.img
                              src={imageUrl}
                              alt={tab.mainTitle}
                              className="w-[110%] md:w-[130%] h-auto object-contain drop-shadow-2xl transform translate-x-6 translate-y-6 md:translate-x-12 md:translate-y-12"
                              initial={{ y: 10, opacity: 0 }}
                              animate={{ y: 0, opacity: 1 }}
                              transition={{ duration: 0.5, delay: 0.1 }}
                            />
                          )}

                          {/* Subtle floating animation overlay */}
                          <motion.div
                            className="absolute inset-0 z-20 pointer-events-none"
                            animate={{ y: [0, -10, 0] }}
                            transition={{ repeat: Infinity, duration: 6, ease: 'easeInOut' }}
                          />
                        </div>
                      </div>
                    </motion.div>
                  )
                })}
              </AnimatePresence>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
