'use client'

import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Media } from '@/payload-types'

// Local type definition until Payload types are regenerated
export type DomainsBlockProps = {
  title: string
  subtitle: string
  tabs: {
    id?: string // Generated by Payload
    tabLabel: string
    moduleTag?: string | null
    subTitle?: string | null
    mainTitle: string
    description: string
    hardware?: string | null
    image: number | Media
  }[]
}

export const DomainsBlock: React.FC<DomainsBlockProps> = (props) => {
  const { title, subtitle, tabs } = props
  const [activeTabId, setActiveTabId] = useState<string | null>(null)

  // Initialize active tab once tabs are available
  useEffect(() => {
    if (tabs && tabs.length > 0 && !activeTabId) {
      setActiveTabId(tabs[0].id || '0')
    }
  }, [tabs, activeTabId])

  // Helper to get image URL safely
  const getImageUrl = (media: number | Media | null | undefined) => {
    if (!media) return ''
    if (typeof media === 'number') return '' // Should ideally resolve relation
    return media.url || ''
  }

  if (!tabs || tabs.length === 0) return null

  return (
    <section className="overflow-hidden bg-smatch-black py-32 text-white">
      <div className="container mx-auto max-w-7xl px-4">
        {/* Section Header */}
        <div className="mb-24 text-center">
          <h2 className="mb-4 font-heading text-3xl font-bold tracking-tight md:text-4xl">
            {title}
          </h2>
          <p className="mx-auto max-w-2xl font-sans text-base text-gray-500">
            {subtitle}
          </p>
        </div>

        <div className="grid grid-cols-1 items-start gap-12 lg:grid-cols-12">
          {/* LEFT: Navigation Tabs */}
          <div className="flex flex-col pt-4 lg:col-span-3">
            {tabs.map((tab, index) => {
              const tabId = tab.id || index.toString()
              const isActive = activeTabId === tabId

              return (
                <button
                  key={tabId}
                  onClick={() => setActiveTabId(tabId)}
                  className={`
                    group relative flex flex-col items-start p-6 text-left transition-all duration-300
                    ${isActive ? 'opacity-100' : 'opacity-40 hover:opacity-70'}
                  `}
                >
                  {/* Active Indicator Line */}
                  <div
                    className={`absolute inset-y-6 left-0 w-[2px] transition-colors duration-300 ${
                      isActive ? 'bg-smatch-gold' : 'bg-gray-800'
                    }`}
                  />

                  <span className="mb-2 font-mono text-sm font-bold text-smatch-gold">
                    {String(index + 1).padStart(2, '0')}.
                  </span>
                  <span className="max-w-[150px] font-heading text-xl font-bold leading-tight">
                    {tab.tabLabel}
                  </span>
                </button>
              )
            })}
          </div>

          {/* RIGHT: Content Card */}
          <div className="lg:col-span-9">
            <div className="relative flex min-h-[500px] flex-col justify-between rounded-2xl border border-white/5 bg-[#0F0F0F] p-8 md:p-12">
              <AnimatePresence mode="wait">
                {tabs.map((tab, index) => {
                  const tabId = tab.id || index.toString()
                  if (tabId !== activeTabId) return null

                  const imageUrl = getImageUrl(tab.image)

                  return (
                    <motion.div
                      key={tabId}
                      initial={{ opacity: 0, x: 10 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: -10 }}
                      transition={{ duration: 0.3 }}
                      className="grid h-full grid-cols-1 gap-12 md:grid-cols-2"
                    >
                      {/* Text Content */}
                      <div className="relative z-10 flex h-full flex-col">
                        <div className="mb-6">
                          <span className="font-mono text-[10px] uppercase tracking-widest text-gray-600">
                            {tab.moduleTag}
                          </span>
                        </div>

                        <h4 className="mb-2 text-sm font-bold text-smatch-gold">
                          {tab.subTitle}
                        </h4>

                        <h3 className="mb-6 font-heading text-4xl font-bold leading-[1.1] text-white md:text-5xl">
                          {tab.mainTitle}
                        </h3>

                        <p className="mb-12 max-w-sm font-sans text-sm leading-relaxed text-gray-500">
                          {tab.description}
                        </p>

                        <div className="mt-auto border-t border-white/5 pt-6">
                          <span className="mb-1 block font-mono text-[10px] uppercase text-gray-600">
                            Hardware
                          </span>
                          <span className="font-mono text-xs text-gray-400">
                            {tab.hardware}
                          </span>
                        </div>
                      </div>

                      {/* Visual / Image Area */}
                      <div className="relative flex min-h-[300px] items-center justify-center md:min-h-0">
                        {/* The "Holo-Platform" Base Effects */}
                        <div className="pointer-events-none absolute bottom-10 left-1/2 size-48 -translate-x-1/2 rounded-full bg-smatch-gold/5 blur-2xl" />

                        {/* Tech Decorative Lines Container */}
                        <div className="pointer-events-none absolute inset-0 rounded-lg border border-white/5 opacity-50">
                          <div className="absolute left-0 top-0 size-2 border-l border-t border-smatch-gold" />
                          <div className="absolute right-0 top-0 size-2 border-r border-t border-smatch-gold" />
                          <div className="absolute bottom-0 left-0 size-2 border-b border-l border-smatch-gold" />
                          <div className="absolute bottom-0 right-0 size-2 border-b border-r border-smatch-gold" />
                        </div>

                        {/* ACTUAL IMAGE RENDER */}
                        <div className="relative z-10 flex size-full items-center justify-center">
                          {imageUrl && (
                            <motion.img
                              src={imageUrl}
                              alt={tab.mainTitle}
                              className="h-auto w-[110%] translate-x-6 translate-y-6 object-contain drop-shadow-2xl md:w-[130%] md:translate-x-12 md:translate-y-12"
                              initial={{ y: 10, opacity: 0 }}
                              animate={{ y: 0, opacity: 1 }}
                              transition={{ duration: 0.5, delay: 0.1 }}
                            />
                          )}

                          {/* Subtle floating animation overlay */}
                          <motion.div
                            className="pointer-events-none absolute inset-0 z-20"
                            animate={{ y: [0, -10, 0] }}
                            transition={{ repeat: Infinity, duration: 6, ease: 'easeInOut' }}
                          />
                        </div>
                      </div>
                    </motion.div>
                  )
                })}
              </AnimatePresence>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
